---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: crl-docker.jfrog.io/carnegierobotics/concourse-ansible-resource
    username: ((artifactory_registry_user))
    password: ((artifactory_registry_token))
    tag: "latest"

run:
  path: ansible
  args:
  - -c
  - local
  - -m
  - setup
  - all

